// <auto-generated />
using System;
using BlockchainApi.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlockchainApi.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlockCypherContext))]
    [Migration("20260409135456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BlockchainApi.Api.Domain.Models.BlockCypher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Coin");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Coin", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("BlockCyphers");
                });
#pragma warning restore 612, 618
        }
    }
}
